random_state: 1
shuffle_data: true
training_size: 0.9
validation_split: 0.1
input_length: 60
output_length: 5
hyperparameter_space:
  feature_columns:
    - [ 'day_of_week', 'open_scaled','high_scaled','low_scaled','close_scaled','volume_scaled','change_scaled','changePercent_scaled' ]
  dropout_rate: [ 0.0, 0.1, 0.2 ]
  optimizer: [ 'adam' ]
  loss_function: [ 'mean_squared_error' ]
  layer_size: [ 10, 20, 30, 40, 50, 100, 500 ]
  nof_hidden_layers: [ 1, 2, 3, 4, 5 ]
  epochs: [ 30 ]
  batch_size: [ 32 ]

